/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import bridge.Sandwich;
import factory.Factura;
import javax.swing.JOptionPane;
import modelo.Pedido;

/**
 *
 * @author Santiago
 */
public class VistaInfoFactura extends javax.swing.JFrame {

    /**
     * Creates new form VistaInfoFactura
     */
    VistaMenu vistaMenu;
    Factura factura;

    public VistaInfoFactura(VistaMenu vistaMenu, Factura factura) {
        initComponents();
        setLocationRelativeTo(this);
        this.vistaMenu = vistaMenu;
        this.factura = factura;
        JOptionPane.showMessageDialog(null, "id: " + factura.getId());
        desactivarCampos();
        completarFactura();
    }

    private void desactivarCampos(){
        txtCarne.setVisible(false);
        txtSalchicha.setVisible(false);
        txtPollo.setVisible(false);
        txtJamon.setVisible(false);
        txtTomate.setVisible(false);
        txtPepinillos.setVisible(false);
        txtLechuga.setVisible(false);
        txtCebolla.setVisible(false);
        txtMayonesa.setVisible(false);
        txtBbq.setVisible(false);
        txtRosada.setVisible(false);
        txtMostaza.setVisible(false);
        txtQueso.setVisible(false);
    }
    
    private void activarCampos(Sandwich sandwich){
        //PAN
        if(sandwich.isPanGriego()){
            txtTipoPan.setText("Griego");
        }
        if(sandwich.isPanIntegral()){
            txtTipoPan.setText("Integral");
        }
        if(sandwich.isPanNormal()){
            txtTipoPan.setText("Normal");
        }
        //PROTEINAS
        if(sandwich.isCarne()){
            txtCarne.setVisible(true);
        }
        if(sandwich.isSalchicha()){
            txtSalchicha.setVisible(true);
        }
        if(sandwich.isJamon()){
            txtPollo.setVisible(true);
        }
        if(sandwich.isPollo()){
            txtPollo.setVisible(true);
        }
        //VEGETALES
        if(sandwich.isTomate()){
            txtTomate.setVisible(true);
        }
        if(sandwich.isPepinillos()){
            txtPepinillos.setVisible(true);
        }
        if(sandwich.isLechuga()){
            txtLechuga.setVisible(true);
        }
        if(sandwich.isCebolla()){
            txtCebolla.setVisible(true);
        }
        //SALSAS
        if(sandwich.isMayonesa()){
            txtMayonesa.setVisible(true);
        }
        if(sandwich.isBBQ()){
            txtBbq.setVisible(true);
        }
        if(sandwich.isRosada()){
            txtRosada.setVisible(true);
        }
        if(sandwich.isMostaza()){
            txtMostaza.setVisible(true);
        }
        if(sandwich.isQueso()){
            txtQueso.setVisible(true);
        }
        
    }
    
    private void completarFactura() {
        txtNumeroFactura.setText(String.valueOf(factura.getId()));
        txtCedulaCliente.setText(String.valueOf(factura.getCedulaCliente()));
        Sandwich sandwich = factura.getPedido().getSandwich();
        activarCampos(sandwich);
        txtTotal.setText("$" + String.valueOf(factura.getImporte()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTipoPan = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCarne = new javax.swing.JLabel();
        txtSalchicha = new javax.swing.JLabel();
        txtJamon = new javax.swing.JLabel();
        txtPollo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTomate = new javax.swing.JLabel();
        txtPepinillos = new javax.swing.JLabel();
        txtLechuga = new javax.swing.JLabel();
        txtCebolla = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMayonesa = new javax.swing.JLabel();
        txtBbq = new javax.swing.JLabel();
        txtRosada = new javax.swing.JLabel();
        txtMostaza = new javax.swing.JLabel();
        txtQueso = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroFactura = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtCedulaCliente = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("QWAY");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resumen pedido", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel4.setText("Pan: ");

        txtTipoPan.setText("tipoPan");

        jLabel6.setText("Proteínas:");

        txtCarne.setText("Carne ($0.7)");

        txtSalchicha.setText("Salchicha ($0.3)");

        txtJamon.setText("Jamón ($0.3)");

        txtPollo.setText("Pollo ($0.5)");

        jLabel7.setText("Vegetales:");

        txtTomate.setText("Tomate ($0.2)");

        txtPepinillos.setText("Pepinillos ($0.3)");

        txtLechuga.setText("Lechuga ($0.2)");

        txtCebolla.setText("Cebolla ($0.3)");

        jLabel8.setText("Salsas:");

        txtMayonesa.setText("Mayonesa ($0.5)");

        txtBbq.setText("Bbq ($0.7)");

        txtRosada.setText("Rosada ($0.2)");

        txtMostaza.setText("Mostaza ($0.5)");

        txtQueso.setText("Queso ($0.2)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCarne)
                                    .addComponent(txtJamon))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPollo)
                                    .addComponent(txtSalchicha)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel6))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel4)
                        .addGap(24, 24, 24)
                        .addComponent(txtTipoPan))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTomate)
                                    .addComponent(txtLechuga))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCebolla)
                                    .addComponent(txtPepinillos)))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(269, 269, 269)
                            .addComponent(jLabel8))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(185, 185, 185)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtMayonesa)
                                    .addGap(26, 26, 26)
                                    .addComponent(txtBbq))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtRosada)
                                    .addGap(41, 41, 41)
                                    .addComponent(txtMostaza))
                                .addComponent(txtQueso)))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTipoPan))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSalchicha)
                            .addComponent(txtCarne))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJamon)
                            .addComponent(txtPollo))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPepinillos)
                            .addComponent(txtTomate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLechuga)
                            .addComponent(txtCebolla))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBbq)
                    .addComponent(txtMayonesa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRosada)
                    .addComponent(txtMostaza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtQueso)
                .addGap(38, 38, 38))
        );

        jLabel2.setText("Factura No.");

        txtNumeroFactura.setText("numero");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jLabel10.setText("C.C cliente: ");

        txtCedulaCliente.setText("cc");

        jLabel9.setText("TOTAL:");

        txtTotal.setText("total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumeroFactura)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCedulaCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(txtTotal)
                .addGap(117, 117, 117))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(265, 265, 265))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumeroFactura))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCedulaCliente)
                    .addComponent(jLabel9)
                    .addComponent(txtTotal))
                .addGap(13, 13, 13)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        VistaPedido vistPedido = new VistaPedido(vistaMenu);
        vistPedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VistaInfoFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VistaInfoFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VistaInfoFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VistaInfoFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VistaInfoFactura().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtBbq;
    private javax.swing.JLabel txtCarne;
    private javax.swing.JLabel txtCebolla;
    private javax.swing.JLabel txtCedulaCliente;
    private javax.swing.JLabel txtJamon;
    private javax.swing.JLabel txtLechuga;
    private javax.swing.JLabel txtMayonesa;
    private javax.swing.JLabel txtMostaza;
    private javax.swing.JLabel txtNumeroFactura;
    private javax.swing.JLabel txtPepinillos;
    private javax.swing.JLabel txtPollo;
    private javax.swing.JLabel txtQueso;
    private javax.swing.JLabel txtRosada;
    private javax.swing.JLabel txtSalchicha;
    private javax.swing.JLabel txtTipoPan;
    private javax.swing.JLabel txtTomate;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
